<div id="content_atm" class="ui-grid-b">
	<div class="ui-block-b"><div style="margin:2.5px;"><a href="javascript:void(0);" id="ABB" name="banknet" onclick="selectBank(this);" class="ui-link"></a></div></div>
	<div class="ui-block-b"><div style="margin:2.5px;"><a href="javascript:void(0);" id="ACB" name="sml" onclick="selectBank(this);" class="ui-link"><img align="absmiddle" class="box" src="<?php echo STATIC_PATH ?>/mobile/images/bank/acb.png"></a></div></div>
	<div class="ui-block-b"><div style="margin:2.5px;"><a href="javascript:void(0);" id="AGB" name="banknet" onclick="selectBank(this);" class="ui-link"><img align="absmiddle" class="box" src="<?php echo STATIC_PATH ?>/mobile/images/bank/agb.png"></a></div></div>
	<div class="ui-block-b"><div style="margin:2.5px;"><a href="javascript:void(0);" id="BAB" name="sml" onclick="selectBank(this);" class="ui-link"><img align="absmiddle" class="box" src="<?php echo STATIC_PATH ?>/mobile/images/bank/bacab.png"></a></div></div>
	<div class="ui-block-b"><div style="margin:2.5px;"><a href="javascript:void(0);" id="BIDV" name="bidv" onclick="selectBank(this);" class="ui-link"><img align="absmiddle" class="box" src="<?php echo STATIC_PATH ?>/mobile/images/bank/bidv.png"></a></div></div>
	<div class="ui-block-b"><div style="margin:2.5px;"><a href="javascript:void(0);" id="PDAB" name="bank" onclick="selectBank(this);" class="ui-link"><img align="absmiddle" class="box" src="<?php echo STATIC_PATH ?>/mobile/images/bank/dab.png"></a></div></div>
	<div class="ui-block-b"><div style="margin:2.5px;"><a href="javascript:void(0);" id="DAIAB" name="banknet" onclick="selectBank(this);" class="ui-link"><img align="absmiddle" class="box" src="<?php echo STATIC_PATH ?>/mobile/images/bank/daiab.png"></a></div></div>
	<div class="ui-block-b"><div style="margin:2.5px;"><a href="javascript:void(0);" id="EIB" name="exb" onclick="selectBank(this);" class="ui-link"><img align="absmiddle" class="box" src="<?php echo STATIC_PATH ?>/mobile/images/bank/exb.png"></a></div></div>
	<div class="ui-block-b"><div style="margin:2.5px;"><a href="javascript:void(0);" id="GPB" name="sml" onclick="selectBank(this);" class="ui-link"><img align="absmiddle" class="box" src="<?php echo STATIC_PATH ?>/mobile/images/bank/gpb.png"></a></div></div>
	<div class="ui-block-b"><div style="margin:2.5px;"><a href="javascript:void(0);" id="HDB" name="sml" onclick="selectBank(this);" class="ui-link"><img align="absmiddle" class="box" src="<?php echo STATIC_PATH ?>/mobile/images/bank/hdb.png"></a></div></div>
	<div class="ui-block-b"><div style="margin:2.5px;"><a href="javascript:void(0);" id="MB" name="sml" onclick="selectBank(this);" class="ui-link"><img align="absmiddle" class="box" src="<?php echo STATIC_PATH ?>/mobile/images/bank/mb.png"></a></div></div>
	<div class="ui-block-b"><div style="margin:2.5px;"><a href="javascript:void(0);" id="MRTB" name="sml" onclick="selectBank(this);" class="ui-link"><img align="absmiddle" class="box" src="<?php echo STATIC_PATH ?>/mobile/images/bank/mtb.png"></a></div></div>
	<div class="ui-block-b"><div style="margin:2.5px;"><a href="javascript:void(0);" id="NAB" name="banknet" onclick="selectBank(this);" class="ui-link"><img align="absmiddle" class="box" src="<?php echo STATIC_PATH ?>/mobile/images/bank/nab.png"></a></div></div>
	<div class="ui-block-b"><div style="margin:2.5px;"><a href="javascript:void(0);" id="NVB" name="sml" onclick="selectBank(this);" class="ui-link"><img align="absmiddle" class="box" src="<?php echo STATIC_PATH ?>/mobile/images/bank/nvb.png"></a></div></div>
	<div class="ui-block-b"><div style="margin:2.5px;"><a href="javascript:void(0);" id="OCB" name="sml" onclick="selectBank(this);" class="ui-link"><img align="absmiddle" class="box" src="<?php echo STATIC_PATH ?>/mobile/images/bank/ocb.png"></a></div></div>
	<div class="ui-block-b"><div style="margin:2.5px;"><a href="javascript:void(0);" id="OCEB" name="sml" onclick="selectBank(this);" class="ui-link"><img align="absmiddle" class="box" src="<?php echo STATIC_PATH ?>/mobile/images/bank/oceanb.png"></a></div></div>
	<div class="ui-block-b"><div style="margin:2.5px;"><a href="javascript:void(0);" id="PGB" name="sml" onclick="selectBank(this);" class="ui-link"><img align="absmiddle" class="box" src="<?php echo STATIC_PATH ?>/mobile/images/bank/pgb.png"></a></div></div>
	<div class="ui-block-b"><div style="margin:2.5px;"><a href="javascript:void(0);" id="SCB" name="banknet" onclick="selectBank(this);" class="ui-link"><img align="absmiddle" class="box" src="<?php echo STATIC_PATH ?>/mobile/images/bank/scb.png"></a></div></div>
	<div class="ui-block-b"><div style="margin:2.5px;"><a href="javascript:void(0);" id="SGB" name="banknet" onclick="selectBank(this);" class="ui-link"><img align="absmiddle" class="box" src="<?php echo STATIC_PATH ?>/mobile/images/bank/sgb.png"></a></div></div>
	<div class="ui-block-b"><div style="margin:2.5px;"><a href="javascript:void(0);" id="TCB" name="sml" onclick="selectBank(this);" class="ui-link"><img align="absmiddle" class="box" src="<?php echo STATIC_PATH ?>/mobile/images/bank/tcb.png"></a></div></div>
	<div class="ui-block-b"><div style="margin:2.5px;"><a href="javascript:void(0);" id="VAB" name="sml" onclick="selectBank(this);" class="ui-link"><img align="absmiddle" class="box" src="<?php echo STATIC_PATH ?>/mobile/images/bank/vab.png"></a></div></div>
	<div class="ui-block-b"><div style="margin:2.5px;"><a href="javascript:void(0);" id="VCB" name="bank" onclick="selectBank(this);" class="ui-link"><img align="absmiddle" class="box" src="<?php echo STATIC_PATH ?>/mobile/images/bank/vcb.png"></a></div></div>
	<div class="ui-block-b"><div style="margin:2.5px;"><a href="javascript:void(0);" id="VIB" name="sml" onclick="selectBank(this);" class="ui-link"><img align="absmiddle" class="box" src="<?php echo STATIC_PATH ?>/mobile/images/bank/vib.png"></a></div></div>
	<div class="ui-block-b"><div style="margin:2.5px;"><a href="javascript:void(0);" id="VPB" name="sml" onclick="selectBank(this);" class="ui-link"><img align="absmiddle" class="box" src="<?php echo STATIC_PATH ?>/mobile/images/bank/vpb.png"></a></div></div>
	<div class="ui-block-b"><div style="margin:2.5px;"><a href="javascript:void(0);" id="VTB" name="bank" onclick="selectBank(this);" class="ui-link"><img align="absmiddle" class="box" src="<?php echo STATIC_PATH ?>/mobile/images/bank/vtb.png"></a></div></div>
</div>